### ISSUE TITLE
Error: EINVAL

### ISSUE THREAD

**Issue by zwhitchcox** [webpack/memory-fs#24]
```
/home/zane/src/ashworthfirm/node_modules/memory-fs/lib/MemoryFileSystem.js:44
                        throw new MemoryFileSystemError(errors.code.EINVAL, path);
         ^
Error: invalid argument
    at pathToArray (/home/zane/src/ashworthfirm/node_modules/memory-fs/lib/MemoryFileSystem.js:44:10)
    at MemoryFileSystem.mkdirpSync (/home/zane/src/ashworthfirm/node_modules/memory-fs/lib/MemoryFileSystem.js:139:13)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (/home/zane/src/ashworthfirm/node_modules/memory-fs/lib/MemoryFileSystem.j
s:279:34)
    at Compiler.<anonymous> (/home/zane/src/ashworthfirm/node_modules/webpack/lib/Compiler.js:229:25)
    at Compiler.applyPluginsAsync (/home/zane/src/ashworthfirm/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.emitAssets (/home/zane/src/ashworthfirm/node_modules/webpack/lib/Compiler.js:226:7)
    at Watching.<anonymous> (/home/zane/src/ashworthfirm/node_modules/webpack/lib/Compiler.js:54:18)
    at /home/zane/src/ashworthfirm/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/home/zane/src/ashworthfirm/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/home/zane/src/ashworthfirm/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/home/zane/src/ashworthfirm/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/home/zane/src/ashworthfirm/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/home/zane/src/ashworthfirm/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/home/zane/src/ashworthfirm/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/home/zane/src/ashworthfirm/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.applyPluginsAsync (/home/zane/src/ashworthfirm/node_modules/tapable/lib/Tapable.js:60:69)
```

**Comment by sokra** [comment]
You provided an invalid value...

What's the issue?

**Comment by zwhitchcox** [comment]
I don't remember
