### ISSUE TITLE
What do you think of this?

### ISSUE THREAD

**Issue by megamindbrian** [webpack/memory-fs#43]
https://github.com/megamindbrian/jupytangular/blob/master/Utilities/file%20system.ipynb

**Comment by megamindbrian** [comment]
Just dropping this off, as you can see from the output, Angular-CLI is running excellently out of memory, but when I get to installing with NPM, open and symlink starts failing:

```
installing ng
  create .editorconfig
  create README.md
  create src/app/app.component.css
  create src/app/app.component.html
  create src/app/app.component.spec.ts
  create src/app/app.component.ts
  create src/app/app.module.ts
  create src/assets/.gitkeep
  create src/environments/environment.prod.ts
  create src/environments/environment.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/polyfills.ts
  create src/styles.css
  create src/test.ts
  create src/tsconfig.app.json
  create src/tsconfig.spec.json
  create src/typings.d.ts
  create .angular-cli.json
  create e2e/app.e2e-spec.ts
  create e2e/app.po.ts
  create e2e/tsconfig.e2e.json
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Project 'new-portal' successfully created.
Already imported
[ 'import notebook.ipynb', 'interpret all notebooks.ipynb' ]
installing module
  create src/app/app-server.module.spec.ts
  create src/app/app-server.module.ts
  WARNING Module is generated but not provided, it must be provided to be used
Already imported
[ 'import notebook.ipynb', 'interpret all notebooks.ipynb' ]
open (/Users/briancullinan/.npm/_cacache/content-v2/sha512/bc/01/e12d70dabf931747c0d1c119db83bc577c2aee25be71dc93753003be3efcca7394a755842d4a99f373f35f379291aec795a69028254bb540044d4696e61c) 
open (/Users/briancullinan/.npm/_cacache/content-v2/sha512/28/e8/54a882f524df6130b1cfbd0fd45133dca28c864cb05ed8fc0e52014a122fe33504c7ef81276007c537f7db9722dd6d9c5ec7f09be2279918dd5af3aee857) 
open (/Users/briancullinan/.npm/_cacache/content-v2/sha512/99/e3/7d90de07fa34f724d5f3ef8e66fbdb69d9778237b937fd4384c6d8ed780e18e3521855f62f30ce5acd3e43166c779818b37f48cf67c59e0da771d1f406e0) 
open (/Users/briancullinan/.npm/_cacache/content-v2/sha512/02/09/5edb4c5676747f08d51d0f22487badae36df8e6d410563319ef0189e4fb9140022a977563ac426ef4c46ac5ced6e505e7a2d6892e07e95aebc79e40ec4fa) 
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENODATA: Cache input stream was empty
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
open (/Users/briancullinan/.npm/_cacache/tmp/f0e4a106) 
Unhandled rejection Error: EBADF: bad file descriptor, write
    at Object.fs.writeSync (fs.js:744:20)
    at SyncWriteStream._write (internal/fs.js:75:6)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at SyncWriteStream.Writable.write (_stream_writable.js:241:11)
    at Stdout.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Stdout.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Stdout.Readable.push (_stream_readable.js:134:10)
    at Stdout.Transform.push (_stream_transform.js:128:32)
    at Stdout._transform ([eval]:65:14)
    at Stdout.Transform._read (_stream_transform.js:167:10)
    at Stdout.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
Unhandled rejection Error: ENOENT: no such file or directory, link '/Users/briancullinan/.npm/_cacache/tmp/7536a111' -> '/Users/briancullinan/.npm/_cacache/content-v2/sha512/c9/9f/aae10a42d56a51efee6da4475762f243b2ead47191397e0db63a582c8a7407bd61c403ba2ba74655ee58c6cf9376af389f94a3227343490a59182e3b978d'
Unhandled rejection Error: ENOENT: no such file or directory, link '/Users/briancullinan/.npm/_cacache/tmp/0e79462d' -> '/Users/briancullinan/.npm/_cacache/content-v2/sha512/57/d1/c891ae0f481b6201fb970cf0ddcc011da9d267d081267811bd8d283f37067dad0097137e81c7ecc7306715249ea0dc1f9d77c5ed110c60908a5f0afc26c0'
```

**Comment by megamindbrian** [comment]
Just dropped in memfs and angular-cli is still working perfectly with the typescript mock above:

```
var mock = require('mock-require');
    var memfs = require('memfs');
    var mem = new memfs.Volume;
    var unionfs = require('unionfs');
    var fs = require('fs');
    
    mem.mountSync(root, data);

    // Create a union of two file systems:
    unionfs
        .use(fs)
        .use(mem)
        .replace(fs);
```
Looks like folders are created even with the unionfs usage above, but files are stored in memory.
https://github.com/streamich/memfs

Moving on to testing with NPM now.

**Comment by CMCDragonkai** [comment]
How did you manage to monkey patch `fs` in third party modules? Or did you not do that? I need to do something similar elsewhere, but I prefer not to need to fork the package and change its `require('fs')` to `require('virtualfs')`.
